name: workflow2

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  USER1: Brent
jobs:
  build:
     env:
       USER2_job: Brent2
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4.1.1
       - name: step 2
         env:
           user3_step: Brent3
         run: |
          ls -l
          echo "github repo name is ${{ GITHUB.REPOSITORY }} and branch name is ${{ GITHUB.REF_NAME }} "
          echo "Value for variable user1, user2 and user3 are $USER1 $USER2_job $user3_step"
          pwd
          java -version
       - run: echo " Print value of user 3 $user3"
  test:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4.1.1
       - name: step 2
         run: |
          ls -l
          echo "github repo name is ${{ GITHUB.REPOSITORY }} and branch name is ${{ GITHUB.REF_NAME }} "
          echo "Value for variable user1, user2 and user3 are $USER1 $USER2 $user3"     
